assets: third_party/LIBERO/libero/libero/assets
bddl_files: third_party/LIBERO/libero/libero/bddl_files
benchmark_root: third_party/LIBERO/libero/libero
datasets: third_party/LIBERO/libero/datasets
init_states: third_party/LIBERO/libero/libero/init_files
