defaults:
  - _self_
  - algorithm: dummy
  - dataset: video_folder
  - model: autogaze
  - task: siglip_video_feature_reconstruction
  - trainer: trainer

# remove hydra logging because we have our own
hydra:
  run:
    dir: .
  output_subdir: null